name: CI

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: write

jobs:
  build:
    needs: test
    name: Building
    runs-on: ${{ startsWith(github.ref, 'refs/tags/v') && 'ubuntu-latest' || 'ndte-large' }}
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - uses: actions/checkout@v4

      - name: Set version (if tag release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "BUILD_TYPE=tagged_release" >> $GITHUB_ENV

      - name: Set version (if main)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "VERSION=main" >> $GITHUB_ENV
          echo "BUILD_TYPE=master_build" >> $GITHUB_ENV

      - name: Set vars
        run: |
          echo "FULL_IMAGE_NAME=nephroflow.azurecr.io/superset_base:${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Set version stamp (when tag release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          bin/stamp

      - name: Build, push and sign docker image
        uses: nephroflow/github-actions/ndte-docker-action@main
        id: docker_push
        with:
          client-id: ${{ secrets.AZURE_GITHUB_ACR_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MAIN_SUBSCRIPTION_ID }}
          full-image-name: ${{ env.FULL_IMAGE_NAME }}
          cosign-key: ${{ secrets.COSIGN_KEY }}
          secrets: |
            BUNDLER_AUTH=${{ secrets.BUNDLER_USERNAME }}:${{ secrets.BUNDLER_TOKEN }}

      - name: Send message to Slack
        if: env.BUILD_TYPE == 'tagged_release'
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: dev-notifications
          slack-optional-icon_emoji: ":nephroflow:"
          slack-text: "New version released: *${{ github.event.repository.name }} <${{ steps.create_release.outputs.url }}|${{ env.VERSION }}>* is ready to deploy. :tada:"
